"use client";

import React from "react";
import { motion } from "framer-motion";

export const AsciiIndonesia = ({
    opacity = 0.15,
    isTop = false
}: {
    opacity?: number,
    isTop?: boolean
}) => {
    // Highly detailed ASCII Map provided by user
    const indonesiaMap = `
       i                                                                                                                                                                                                                                                                                                                                                                                                                  
     iiddmm                                                                                                                                                                                                                                                                                                                                                                                                     
      idddddim                                                                                                                                                                                                                                                                                                                                                                                                  
      idddd0ddddimmmdddiimi                                                                                                                                                                                                                                                                                                                                                                                     
       dddd0dddddddddddddd0di                                                                                                                                                                                                                                                                                                                                                                                   
        dddd0dd00dd0dddddd0ddd                                                                                                                                                                                                                                                        0                                                                                                                         
         dddddd0dddddddd0ddddddd                                                                                   i                                                                                                                                                               0 d0                                                                                                                         
          ddddddd00ddddd0dddddddd                                                                                                                                                     v  vvv  v    v                                                                              010                                                                                                                           
            dddddddd0dddd0dd0ddmid                                                                                  id                                                               vrimddmiiddiiirrvvr                                                                          616                                                                                                                           
              ddddd0ddddddddddidddddi                                                                              dddd                                                             vd000000d00d00d0diiim                                                                        066                                                                                                                            
                dddddd0ddddddidddddddim                                                                           dddddi                                                           vrd00dd00ddddd0d00d0d                                                               00         06                                                                                                                            
                  idddd000dddidddd000ddddi                                                                          ddd                                                             mdd0d00d0000000d0000                                                               616         0                                                                                                                            
                      ddddddddmdddddd00dd0ddm                                                       dd                                                                             vr00dd00dd0ddd000dddd                                                                660                                                                                                                                     
                       ddd0dddiddd00dddddddddd0                                                 d   dd                                                                             vdd00d00d0000dd00dd                                                                                                                                                                                                          
           dd           0dd0ddid0dddddd0dd00dddd                                               idi  i            i        dd                                                    vrri0d0dd0dd0d00d0d000d                                                                                                                                                                                                         
           ddddm          dddddiddddiddddddddddddd                                              i   i                     i                                                     v0d00d00d000dd0d0ddd000d                                                               60                                                                                                                                       
            dddddd         dd0didd0ddddd0dd00dddddi                                                                         dd                                                  vmd0dd0dd00ddidiidddiiddi                                                              d                        1WW1                                                                                                            
               iddi    im  dddddddddddddddd0ddddddid 0dddd                                                                                                                   vvmdd00d0000diiddddd00d0diddd                                                             00                  61066WWW1                                                                                                            
                  dd  iddi   idid0d00dddd00dd0ddddidddddddddddd                                                                iiv                                           vi00d0dd0dd0did00d0d0dd0000d                                                              d                   61W11WW1                                                                                                             
                                 iddddddddddd00dddidddddddddddd                                                               00i                                           vvi0dd00d00ddi0d0d00d00dd0d0i                                                           00                    1WW6  0                                                                                                               
                                  diidd0ddd0ddddddmdddddddddddddddimd                                                        dd00rv                                         vd0d0d0dd00didd00d0dd00d00d0dddi                                                     00616                   6WWWWd  66d                                                                                                            
                       dddd        iid0dd00dddddddmddddddd0d0dddddddd                                                       d0dd00mvv                  vriiiiivvv   vvrrrrrvi0d00d00ddiid0dd0d000dd00dd00d00dd                   d0                             6111116                  1WWWW611WWW1                                                                                                           
                       ddd0dd        d00dd00ddddiddddd0ddddddddddddddidim   i    id idd                                    d00dd00ddmrv        v       m00d0d0dddmmrridii00ddidddddiidd00d00dd0dd00d0dd00d00000d                6111160                       06111116         16       6WWWW16WWWWW1                                                                                                           
                         dd0ddd       ddd0dd0dddmdddddddddddddd00ddddddddd ddd iddddddddi                     ddd          d00dd0d000dmvv v vrrrrrrrrii00d00dd0d00dd0did0dd0dddddid0d0d00d00d00d00d00dd00dd0dd000d          66 011111116606001660 00000dd   061111116                   6WW111WWWWW1                                                                                                            
                          dddd        ddddddddiimidddddddd0ddddddddddddddddddddddddd6dddd                      6         dddd0d000d0d00dimmrd0d0ddddd0d0dd00d00d00d00idd0d00ddi00ddd0d0ddd0dd0dd0dd00d0d0dd0d0d00         06166111160d00616111111111001111111111116                    611WW1WWW6d                                                                                                              
                           ddd         dddddddiidmddd0ddddd00dddddddddddddddddddd  dd 0d                                   0000dd0dd0d0d0dd0d000d000d00d0d0dd0dd0ddddiddiddidddid0000d00d00d00d00dd0d0d                  011111111160611111111111111160d111111116                       11WWWWWWWW1W                     0                                                                                      
                                        diddddddddiiddddddd0d000ddddddddddddddd     dd                                     0dd0d00d0000d00d00dd00dd0d0d00d000dd0dddid00ddddd00ddid0ddd00d0d00dd00d000d                  6111660661610d60666166i06d00611d111111616                       111WW1111WWW0                  0                                                                                        
                                   ddd  mdddddd0dddddimddddddddddddddddddddddddd   iiddi                                   idd00dd00d0dd0dd00dd00d00dd00dd00ddd0dmd0d0d00d0ddidd0000d0d00dd00dd0dd00d                  06116                         0dd06d                             6 WWW1    d666  0                                                                                                       
                             i  iddmmi     idddddd0dddiddd0dddddddddddddddddddddi    dddi                                    d00d0dd0d00d00d00d0dd00dd00dd0d00d00id00dd0d00d0diddi00d0d00dd0d00d000d0                 06116            0                                               661 WW1          6660   66611611160                                                                                      
                             i   ddd         dddddd00diddddddddddddddddddddd0ddd   dddddddi                                 d0dd00d00d00d0dd00d00000d00d0d0d0dddidd00d00dd0d00dddidd00dd0000d0dd00dd0                  0110            6 00000                                       111666WWW            16    611W11WWWW6       000d0                                                                         
                                 ddd          id0d00ddddidddddd0dddddd0ddddddddm   dddd  i                                  d0ddd0dd0ddd00dd0d00ddd0dd0d00dddddii0000d00d00dd0dd0id00d0d000d00dd00000d                 6116             61660      0d0                                11WWW61W1              16   611110d6     01WWWWWWW16                                                                      
                                 ii             ddd0000dddiiddddddddddddddddii      ddd                                      00d00000d00ddd00d00d00dddiidiiiddddd0dd0ddd0d0d0000ddidd00dd0d00d0dd0000d                d6111            d 6  dd0d00611166                              611WW111W166                 1600  d66611WWWWWWWWWWWW1i16610          611110                                              
                                    ddd          idddddddddddiidiiidd0ddidddddddiidii                                         d0d000dd00d0d00d00d0ddidd0ddd00d00d00d00d00d00dd0d00did00d00d000d0d0d00d               061111166       061606611111111111                                0 161W d010                611W1601WWWWWWWWWWWWWWWWW0WWWWW1     11    611WW10                                            
                                   idddd          dd0ddd00d0ddimddddiiiddddddddddddddi                                        dd00000d0d0dd00d0dddid0dd00dd0dd00d0dd0d00dd00dd0dd00ddidd000dd0000d                  611111111     61111111111116d0060                                 616     66        6 666     6WWW6WWWWWWWWWWWWWWWW101WWWWWWW    1W6      1WWW16                                          
                                   dddddd         dddd00dddd0didddddddddddd00ddddddddd                                        ddddi 0dd00dd0d0ddidd00d00dd00dd0d00d00d00dd00000dd00dimd0d00d00ddd                  61d61111111166006111111111116661116110                              016W16               006      11WWWWWWWWWWWWWWWW1061WWWWWWW1     0       06d06 1          0                              
                                    dddddd          dddddddddiddddd00dd0dddddd0ddddddi       dddddd                       d0        d0d00d00diid0d000dd0d00d00dd0d0dd0d00ddd0dd0ddidid00dd0d0i                     6166011111111111111111111110  61666666      00d                     66WWWWW1 0                6    111161WWWWWWWWW060WWWWWWWWWW1       66660dd000         061WWW6d    1                      
                                      dddd           ddddiiidddddddd0ddddddd0dddiiiiidi     dddddddd                     dd0        0dd0dd0dmi00ddd00d00dd0d0d00d000d0d00d000d000dd0ddd0d0dd0                      61116011111111111111116660     0 00066  0  1WWWW11111166111601       111111116          000111W1          d01WWWW161WWWWWWWWWW16          6111WWWW11116011WWWWWWWWW1116                      
                                       0im  i         dddiddd0dd00ddd0dd0ddd0iddddddddddd  ddddd0dddi                               d00d00d0did00dd00000d00dd0d0dd0d0d00dd0d0dd0ddmddid00d00                       61111d0066d61111116616          61   000601WWWW111116111111106         6                 61WWWW6            1WWWWW0WWWWWWWWWWWW616            60161160 01WWWWWWWWWWWWWW1106                  
                                           ddd        idddmddd0dddddddddddiidmdddddddddddd ddddddd00d                                d0d0dd00id0d00dd0ddd00d00d00dd00d00d00d00d0did00didddd0d                     11116061166100606111166                 6   060          1W                                 6006d             1WWWWdWWWWWWWWWWWW111                1661WWWWWWWWWWWWWWWWWWWWW11d   0           
                                            ddii       ddidiidddddd0dddiiiididdddddddd0ddddddddd dddddii                             d00d0dd0dd0000d000d00dd0dd00dd0dddd00d00ddid00d00idddiid                    d111166111111111660000611                                  11                                    0               d0 i0666166161WW16 6              1WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW16116      
                                               dd0      iddddiiddddiddiddddddddddd00ddddddddddddiddd0ddddi      dddddi               ddd00dd0di00dd0dd0dd00d00d00d00000d0dd00idd00d00d0dd00dd                  66111116d1111111111111116d111                                                                                    01010 01WWWWWWWWWWWW6W66          01WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW6m   
                                               dddd      idddddddmdddddddddddddddddddddddd0ddddddidddddddi d  ddddddddd              ddd00dddidd0d0d0d00d0ddd0dd0dd0dd00d0diid0dd0000d00dd0d                   61111110611111160 dd0d616d11166                                               6 11111111061W111                 6WWWWWWWWWWWWWWWWWWWWW6661      0 011WWWWWWWWWWWWWWWW1611WWWWWWWWWWWWWWWWWWW1m   
                                                 ddd       dddddddiiid00ddddd0ddddd0d00d0d0dddddddddidddddii  iddddddd                0diidid0ddd000000d00d0000d00d00d0000di00dd000000d00d0                    61111160111116     0110066000060                              d 611116d     0611WWWWWWWWWWWWWWWWWWW10            6611WWWWWWWWWWWWWWWWWW016      01W16001W111166111W10i11011WWWWWWWWWWWWWWWWW1r   
                                                  dd        dddddddddidddddddd00ddd0dddd0ddddddddddd   id      idddddd                             i0dd00dd0ddd 0dd0dddd0did00d0000dd0000dd                    611110061111116   61111111111606                             6WWWWWWWWW6  6616W11WWWWW1WWWWWWWWWWWWWW16             01WWWWWWWWW1WWWWWWWW01600061WWWWWWW0666611W1660616WW106061WWWWWWWWWWWWWW1r   
                                                   i          idddd0dddiid0ddd0ddd0d0ddd0dddddddddd                                                dddddddddi    6 0dd0ddi00000ddd00dd00000d                   611116011111116   11111111111160     d                       1WWWWWWWWWW1 01 616W11111W611116061WWWWWW1               61WWWWWWWWWWWWWWWW11WWWWWWWWWWWWWWWWWWWWWWWWWW01WWWWWW10006611WWWWWWWW1r   
                                                                idddddiiid0dddd0ddddd0dddddddddddd                                                  i                     dddd00d00dddddd00d                    060  111111116   61111111111160    d0                         1WWWWWWWW1     1WW11116           611WWW1              01WWWWW1611WWWWWWWW06WWWWWWWWWWWWWWWWWWWWWWWWW0WWWWWWWWWWWW116066661116r   
                                                                  d0ddiddd0dddddd0ddd00dd0diididddd                                                                        dd00d0dddii  00d                          611111116     66111111111166  00                           01116  11    066                   6W16   6           1WWWWW6   11WWWWWWW60WWWWWWWWWWWWWWWWWWWWWW601WWWWWWWWWWWWWWWWWW111616r   
                                                                   dddddmddd0ddddddd0dddddiddddiid                                                                         d0dddi       dd                            1111111        06111111111666116                                16d                                666          1111660    666661101WWWWWWWWWWWWWWWWWWWWW101WWWWWWWWWWWWWWWWWWWWWWWWW1r   
                                                                     iddddddid0d0dd0diiiiddd0ddddd                                                                          i                                         61111110        611111111111660                                                                     6                66          01WWWWWWWWWWWWWWWWWWWWWW11WWWWWWWWWWWWWWWWWWWWWWWWWW1r   
                                                                       dddddiiidddddidddd0dd0dddddd                                                                                                                   11111110        111111166666116                                                         6             06                           66111111WWWWWWWWWWWWWWWd66111WWWWWWWWWWWWWWWWWWWWW1r   
                                                                          iddddmddddidddddd0dddd00                                                                                   i                               611111116        611116 66116111d                                                                       6                                    6111WWWWWWWWWW0111660000001WWWWWWWWWWWWWW1r   
                                                                            ddidiiidi00ddd0dd00ddd                                                                                                                   11111116          00060 61111166                                                                                                                 d0111WWWW0WWWWWWWWWWWW1006611WWWWWWWW1r   
                                                                  i            idddddd000dd00ddddd                                                                         r                         d              111111111            616 11101166   0                                                                                0                                  0110WWWWWWWWWWWWWWW1166600666616r   
                                                                 ddd             ddddddd000ddddddd                                                                                                      0          01111111116           6160111111116 66d                                                                     6        1W           11                         11WWWWWWWWWWWWWWWWWWWW111110r   
                                                                   i              idddddd0dddd00dd                                                         m              r                                        06111111666            66  06116d     0d00                                                                     6  11 11        661WW1                          6WWWWWWWWWWWWWWWWWWWWWWWW1r   
                                                                                    id0diddd  dddd r       v                            r                 rrr                                                         0d0    60               0i00         6d                                                                    6   1116         61WWW6                           61WWWWWWWWWWWWWWWWWWWWWW1r   
                                                                                      dd     di drrrrrrrrrrrrrr                         r                                                                                    66                            66                                                                        616         11WWWW1                             1WWWWWWWWWWWWWWWWWWWWW1r   
                                                                                             i   rrrrrrrvrrrrrrrrrrrvrr                                                                                                     066                                                                                                                  6WWWWW61                             WWWWWWWWWWWWWWWWWWWWW1r   
                                                                                           vr  rvrrrrrvrrrrrrrrrrrrrrrrrr                 rrrr                                                                               66                                                                                                                  1WWWW111                             1WWWWWWWWWWWWWWWWWWWWmr   
                                                                                           rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrv v   v        rrrrrrrrrrvrr                                                                       0                                                                                              6                    1WWW111                                1WWWWWWWWWWWWWWWWW1v    
                                                                                            rrrrrrrrrrvrrrrrrrrrrrrrrrrrrrvrrrrrrrrrrrrrrrrrrrrrrrvrrrrrrrr rrrrrrrrrrrr         rrrr                             0             0                                                                                          66                    1W1616                                1WWWWWWWWWWWWWWWWWWWmv   
                                                                                                    vrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrvrrrrrrrrrrrrrrrrrrrrrrrrr     rrrrrr                                        60                                                                 16                       01611                     6                                 11WWWWWWWWWWWWWWWWWWWr   
                                                                                                     rrrrrrrrrrrrrrrrrrrvrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrvrr  v           rr                                        0d000    06                                                        61                   6066WW661                                                     dd061WWWWWWWWWWWWWWWWWWr   
                                                                                                      vrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrm       r                                                           0d    66                                      616     16                  0        6616WWWW0                                                     61WWWWW1WWWWWWWWWWWWWWWWWr   
                                                                                                                rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr                                                                                                6W1WWWWW1    16                 660 0      d11WWW1                                                     1WWWWWWWWWWWWWWWWWWWWWWWWWr   
                                                                                                                    vvrr    r    vvrvrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr     i                                                                 i                       61W1W1W10   6                   11W1 0       0WW10                                                     1WWWWWWWWWWWWWWWWWWWWWWWWWWr   
                                                                                                                                      rrrrrvrrrrrrrrrrrrrrrrrrrrrrrrrriddddddddd      dii       ddddddd di didd         0di                  dddiiiiddd  ddddddddd    00          66  661116    066     06R       1160                                                      1WWWWWWWWWWW11WW1111WWWWWWWWr   
                                                                                                                                          vvvvrrrrrrrrrrrrrrrrrrrrrrrrrrrriddddddddddd  dddddd  ddddddiddddddddddd d0d  diddddddddddi  idii  diddddddddddddddddddddddd                    060061     00              661                                                       6WWWWWWW11W16  d     61WWWWWWr   
                                                                                                                                                          mr    rrrrrrrrrrrriiidddddd  6ddddddddddddddddiddddddddddiddddddddddddddddddddddddddddddddddddd  ddd ii                                                                                                               0    6                01WWWWr   
                                                                                                                                                                       ivrrr    dd dd ddddddd ddddddddddddddddddddd diddddddddddddddddddddddddddi                                                                                                                                                       1WWWr   
                                                                                                                                                                                d      iididiidddddddddddi  ii  i          ii  iidddddiiid                       ddmvvv                                                                                                                                  d1Wr   
                                                                                                                                                                                               iiiii               i  i dd                                  v  vidddvr                                                                                                                                     dr   
                                                                                                                                                                                                                dddddddddddd                             iddrmviddddi                                                                                                                                           
                                                                                                                                                                                                                ddddddddddddddd                         idddddddddddd                                                                                                                                           
                                                                                                                                                                                                                  idddddddddddddm                       dddddddddddi                                                                                                                                            
                                                                                                                                                                                                                        dddddddddi                    dddddddddddd                                                                                                                                              
                                                                                                                                                                                                                          ddddddi                    ddddddddiii                                                                                                                                                
                                                                                                                                                                                                                                       iddd         iddiiii                                                                                                                                                     
                                                                                                                                                                                                                                      idid      idddddd                                                                                                                                                         
                                                                                                                                                                                                                                                dddddd                                                                                                                                                          
    `;

    return (
        <div className={`absolute inset-x-0 ${isTop ? 'top-[-380px]' : 'bottom-[-300px]'} flex items-center justify-center pointer-events-none select-none z-[0]`}>
            <motion.pre
                initial={{ opacity: 0, y: isTop ? -50 : 50, scale: 0.8 }}
                animate={{
                    opacity: opacity,
                    y: 0,
                    scale: 1,
                    color: ["#22d3ee", "#a855f7", "#22d3ee"],
                    textShadow: [
                        "0 0 20px rgba(34, 211, 238, 0.5)",
                        "0 0 40px rgba(168, 85, 247, 0.8)",
                        "0 0 20px rgba(34, 211, 238, 0.5)"
                    ]
                }}
                transition={{
                    duration: 5,
                    repeat: Infinity,
                    repeatType: "mirror",
                    opacity: { duration: 2 },
                    y: { duration: 2 }
                }}
                className="font-mono text-[2px] leading-[1] whitespace-pre text-center tracking-[0.1px] max-w-full"
                style={{
                    fontSize: "clamp(1px, 10vw, 6px)",
                    transformOrigin: "bottom center"
                }}
            >
                {indonesiaMap}
            </motion.pre>

        </div>
    );
};
